"""adding init+false on updated_at column

Revision ID: af78543a6cc2
Revises: dcfeb71153b5
Create Date: 2024-05-23 00:19:56.011081

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'af78543a6cc2'
down_revision: Union[str, None] = 'dcfeb71153b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
